# Generated by Django 3.1.4 on 2021-01-04 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_workout_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
