# Generated by Django 3.1.4 on 2021-03-18 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_auto_20210318_1931'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('friendly_name', models.CharField(blank=True, max_length=254)),
            ],
            options={
                'verbose_name_plural': 'Workout Types',
            },
        ),
        migrations.RemoveField(
            model_name='workout',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='tags',
        ),
        migrations.AddField(
            model_name='workout',
            name='workout_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workouts.workouttype'),
        ),
    ]
