# Generated by Django 3.1.6 on 2021-03-19 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0004_auto_20210319_0936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='muscles_worked',
        ),
    ]
