# Generated by Django 3.1.6 on 2021-03-20 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0005_remove_workout_muscles_worked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='category',
        ),
        migrations.AddField(
            model_name='workouttype',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workouts.category'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='difficulty',
            field=models.CharField(choices=[(1, 'Very Easy'), (2, 'Easy'), (3, 'Medium'), (4, 'Hard'), (5, 'Very Hard')], max_length=12),
        ),
    ]
