# Generated by Django 3.1.6 on 2021-03-21 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0006_auto_20210320_2131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workouttype',
            name='category',
        ),
        migrations.AddField(
            model_name='workout',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='workouts.category'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='difficulty',
            field=models.CharField(choices=[('1', 'Very Easy'), ('2', 'Easy'), ('3', 'Medium'), ('4', 'Hard'), ('5', 'Very Hard')], max_length=12),
        ),
    ]
