# Generated by Django 3.1.6 on 2021-03-23 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('workouts', '0007_auto_20210321_2040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workout',
            old_name='rating',
            new_name='avg_rating',
        ),
        migrations.AlterField(
            model_name='workout',
            name='difficulty',
            field=models.CharField(choices=[('1', 'Light'), ('2', 'Easy'), ('3', 'Medium'), ('4', 'Hard'), ('5', 'Advanced')], max_length=12),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('rating', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', related_query_name='review', to='profiles.userprofile')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', related_query_name='review', to='workouts.workout')),
            ],
        ),
    ]
