# Generated by Django 3.1.6 on 2021-03-23 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0008_auto_20210323_1326'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workout',
            old_name='avg_rating',
            new_name='rating',
        ),
    ]
